"""Discord webhook notifier for the SRE Copilot proactive watcher.

Sends rich Discord embeds containing the RCA summary generated by the ADK
agent whenever an observability threshold is breached.
"""

import logging
from datetime import datetime, timezone
from typing import List, Optional

import httpx

from .config import DISCORD_WEBHOOK_URL, SERVICE_NAME

log = logging.getLogger("copilot.notifier")

# Discord embed colour codes
_COLOUR_RED = 0xE74C3C       # critical / service down
_COLOUR_ORANGE = 0xE67E22    # degraded / high error rate / high latency
_COLOUR_YELLOW = 0xF1C40F    # warning  / slow traces / log errors


def _choose_colour(breaches: List[str]) -> int:
    """Pick an embed colour based on the severity of active breaches."""
    lower = " ".join(breaches).lower()
    if "down" in lower or "health" in lower:
        return _COLOUR_RED
    if "error rate" in lower or "latency" in lower:
        return _COLOUR_ORANGE
    return _COLOUR_YELLOW


def _truncate(text: str, max_len: int = 1024) -> str:
    """Truncate text to Discord's field value limit."""
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."


def send_discord_alert(
    breaches: List[str],
    rca_text: str,
    poll_window_minutes: int = 5,
) -> bool:
    """POST a Discord embed with breach details and full RCA to the webhook.

    Args:
        breaches:             Human-readable list of threshold violations detected.
        rca_text:             Full RCA markdown text generated by the ADK agent.
        poll_window_minutes:  The monitoring window that produced this alert.

    Returns:
        True if the webhook POST succeeded, False otherwise.
    """
    if not DISCORD_WEBHOOK_URL:
        log.warning(
            "DISCORD_WEBHOOK_URL is not configured — skipping Discord notification."
        )
        return False

    now = datetime.now(timezone.utc)
    timestamp_iso = now.strftime("%Y-%m-%dT%H:%M:%SZ")
    display_ts = now.strftime("%Y-%m-%d %H:%M UTC")

    # Build breach field value
    breach_lines = "\n".join(f"• {b}" for b in breaches)

    # Split RCA into chunks if it exceeds Discord's 1024-char field limit
    rca_chunks = []
    remaining = rca_text.strip()
    while remaining:
        chunk = remaining[:1020]
        rca_chunks.append(chunk)
        remaining = remaining[1020:]

    # Build embed fields
    fields = [
        {
            "name": "⚠️ Thresholds Breached",
            "value": _truncate(breach_lines) or "N/A",
            "inline": False,
        },
        {
            "name": f"📋 RCA — Part 1 of {len(rca_chunks)}",
            "value": _truncate(rca_chunks[0]) if rca_chunks else "No RCA generated.",
            "inline": False,
        },
    ]

    # Append additional RCA chunks as separate fields (Discord allows up to 25)
    for idx, chunk in enumerate(rca_chunks[1:], start=2):
        fields.append(
            {
                "name": f"📋 RCA — Part {idx} of {len(rca_chunks)}",
                "value": _truncate(chunk),
                "inline": False,
            }
        )

    fields.append(
        {
            "name": "🕒 Details",
            "value": f"Service: `{SERVICE_NAME}` | Window: last {poll_window_minutes}m | Time: {display_ts}",
            "inline": False,
        }
    )

    payload = {
        "username": "SRE Copilot",
        "avatar_url": "https://cdn-icons-png.flaticon.com/512/4712/4712035.png",
        "embeds": [
            {
                "title": f"🚨 SRE Alert — `{SERVICE_NAME}`",
                "description": (
                    f"**{len(breaches)} threshold(s) breached** during the last "
                    f"{poll_window_minutes}-minute monitoring window."
                ),
                "color": _choose_colour(breaches),
                "fields": fields,
                "footer": {"text": "SRE Copilot · Proactive Watcher"},
                "timestamp": timestamp_iso,
            }
        ],
    }

    try:
        with httpx.Client(timeout=10) as client:
            resp = client.post(DISCORD_WEBHOOK_URL, json=payload)
            resp.raise_for_status()
        log.info("Discord alert sent successfully (HTTP %s).", resp.status_code)
        return True
    except httpx.HTTPStatusError as exc:
        log.error(
            "Discord webhook returned HTTP %s: %s",
            exc.response.status_code,
            exc.response.text[:200],
        )
    except Exception as exc:
        log.error("Failed to send Discord alert: %s", exc)
    return False
